---
title: "Reproducible Document"
author: "rostools"
format: html
editor: visual
---
```{r setup}
#| message: false
#| warning: false
library(tidyverse)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))

```

## Writing R code
2+2
```{r}
2+2
```
## About me 
- Adam Phd student/KU
1. Adam Phd Student/KU
**Climber** *Route Setter*

## Simple Code
```{r}
3*3
```
## Testing for Git
sunny but cold 


##Showing the data
```{r}
post_meal_data

glimpse(post_meal_data)
```
##Plot one continuous variable 
```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x=BMI)) +
  geom_histogram()
```

See @fig-bmi-histo

## Exercise: discrete plots
```{r}
#| fig-cap: "glykemi-count"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

See @fig-group-bar above for a cool plot!

##Plotting two discrete variables 

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi)))+
  geom_bar(position = position_dodge())
```
## Side by side plots

```{r fig-bmi-glyvcemia}
#| fig-cap: "BMI and glycemia side by side"
#| fig-subcap: 
#| - "Distribution of BMI"
#| - "Number of those with glycemia"
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI))+
  geom_histogram()
ggplot(post_meal_data, aes(x = glykemi))+
  geom_bar()
```

